### ISSUE TITLE
Spreadsheet loader error: "Cannot insert nodes into the document because it is empty."

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1003]
Of the 2588 successful records processed for the Boston Deseg collection (https://repository.library.northeastern.edu/loaders/spreadsheet/report/906), 2 records couldn't be updated because of this error:

> Cannot insert nodes into the document because it is empty.

Target records:
https://repository.library.northeastern.edu/files/neu:rx9185844
https://repository.library.northeastern.edu/files/neu:cj82kk87w

The spreadsheet and metadata look fine (I'll share the spreadsheet) over slack.

![2016-08-05_0824](https://cloud.githubusercontent.com/assets/4663073/17437642/dbf61584-5aec-11e6-8355-599da2216345.png)

**Comment by elizoller** [comment]
Curious... 
The job inputs the new template before starting so this shouldn't happen but I'm wondering if its happening somehow because of the fact that these records don't appear to have keywords.

**Comment by elizoller** [comment]
Finally figured out what is going on here- during the processing for personal creators, it ends up passing a hash of first names and last names and since the two sample records have two different personal creators with the same first name, it basically just isn't set up to handle that and ends up making one less creator than it should. Just need to think of a different way to handle it.
