### ISSUE TITLE
Monographs in the Daily Updates emails

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1006]
New files with "Monograph" scholarly object metadata are showing up in the "Daily Non-featured content and collection uploads and updates" email instead of the "Daily featured content uploads and updates" email. Since monographs are featured now, they should be in the "Featured content" emails.

**Comment by elizoller** [comment]
I think this is working as designed. During the creation of a core file, it creates the upload alert which records the category (monographs, etc.). Then the email is created by looking at the upload alerts and separating them by category. This particular file was created through the interface and then the XML was edited to set the 'monograph' in the scholarly object (which also sets the category). When XML is edited, it creates an xml alert instead of an upload alert (which is what sets the 'updated' sections of the featured content emails.

**Comment by sarahjeansweeney** [comment]
Okay, this makes sense.
