### ISSUE TITLE
Uploaded text file missing extension

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1028]
A .txt file was uploaded the other day: https://repository.library.northeastern.edu/files/neu:cj82nf72s

My browser opens the file without a problem, but when I try to download it there's no extension:

<img width="712" alt="2016-08-31_1426" src="https://cloud.githubusercontent.com/assets/4663073/18141291/f6ad1e50-6f86-11e6-8e8c-bcd8efcae960.png">

The original filename was "PrinceMary-TheHistOf-1831.txt" so the .txt must have been stripped along the way.

It looks like we have five text files, though I can't find them to see if this is all text files, or just this particular text file.

**Comment by dgcliff** [comment]
So we definitely recorded the original filename correctly

```<original_filename>PrinceMary-TheHistOf-1831.txt</original_filename>```

So it must be in the act of downloading. I'll look into it.

**Comment by dgcliff** [comment]
Interestingly I can't replicate this in my dev environment. Which points the finger at something to do with Apache, as dev uses Jetty. Will dig some more.

**Comment by dgcliff** [comment]
This (specific) instance has been fixed with a new version of file https://github.com/file/file 5.28 for reference

However, the same problem can be found with this file https://repository.library.northeastern.edu/files/neu:cj82nc15r

This can't be seen, as I've manually changed it's mime type to text/plain, but it used to be text/troff

The content object in that case is a .R code file. So it's not that surprising that something this exotic caused file to mis-guess. Going to create a patch that if we can't figure out the extension from the guessed mimetype, to fall back to text/plain and the extension from the original filename
