### ISSUE TITLE
Can't select the correct "Research Publications" collection for spreadsheet or xml upload

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1063]
I have a bulk upload I need to process for a faculty member using the spreadsheet loader. She'd like the files to go into her Research Publications collection:
https://repository.library.northeastern.edu/collections/neu:m040rw33r

To upload the files, I went to My Loaders, selected the Spreadsheet loader, and selected "New Files + Metadata". neu:m040rw33r is not available for me to select in the "Choose Collection" box. Searching for the exact PID returns nothing. If I enter "research publications", the list of research publication collections is incomplete (I can't get a full screenshot of all the options, so this is just a snippet):
![2016-11-18_1356](https://cloud.githubusercontent.com/assets/4663073/20442574/19f7114c-ad97-11e6-8765-03b6447f7382.png)

If I had to guess, I'd say this list is just the faculty collections migrated from IRis and my research publications collection (that's me at the top).

Same thing for the XML loader's "Choose Collection" box. I should be able to select any DRS collection, including the smart collections generated for employees when they first sign in.

**Comment by elizoller** [comment]
Trying to get a grasp around this ticket. I completely understand that the autocomplete is failing for this purpose. The query that the autocomplete runs off is all of the collections that the current user is the depositor for or has edit access to based on the groups they belong to.

As far as I can tell the employee creation job, that creates the Research Publication collections when a new employee is created, does not automatically assign any groups edit access so I would not expect you to see anyone's Research Publication collections except for your own. Perhaps we should implement an alternate query for admin user that can perform the autocomplete for any collection? I'm not sure how that will perform with thousands of collections though? We could implement the autocomplete in a different way, like by actually performing a query for collections with pid or title of the inputted text instead of using the javascript autocomplete functionality. Although that is probably likely to be slow.

For the Research Publications collections that you do see that are not your own, they do seem to have the edit_access for northeastern:drs:repository:staff. I don't see that being assigned for the automatically created collections, just for collections that go through the create method in the controller, meaning they went through the interface.

Just my thoughts

**Comment by dgcliff** [comment]
Research Publications don't go through the interface, so the ones that do have it, I imagine were affected by a loop to add that group to everything (up to the point that it was done, and then new ones were created without it etc.)

Does autocomplete have merit for someone like Sarah? I can't imagine there is much convenience, and probably delays the interface quite a bit.

**Comment by sarahjeansweeney** [comment]
I don't need autocorrect for these loaders. I think I'd prefer to enter the collection PID or full URL.

**Comment by dgcliff** [comment]
Cool - that's an easy enough fix. I can run a loop to add repo:staff edit to the Smart Collections that don't have them, and alter their creation so new ones will get them after that

**Comment by sarahjeansweeney** [comment]
*autocomplete.

**Comment by dgcliff** [comment]
Should be fixed with 76198c2e30ed5e1db46828f74c2710853341e1f1 and 9e4df3dd03498be2914cd686687ea63e07525296
