### ISSUE TITLE
Spreadsheet uploader: Identifier field

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1065]
During a meeting with RADS and Archives we noticed that we omitted identifier in our MODS mapping for the spreadsheet loader. The "What is the identifier for this object?" field is mapped to relatedItem type="original"/identifier, but nothing maps to the top-level MODS identifier field, so that will need to be added to the spreadsheet mapping.

If possible, I'd like to suggest two changes to the spreadsheet loader mapping:

Add an "Identifier" column that maps to mods:identifier
Change the existing identifier column heading from "What is the identifier for this object?" to "What is the original identifier?" (keep the same mapping).

**Comment by elizoller** [comment]
What would an example of the mods be for the top-level identifier?

**Comment by sarahjeansweeney** [comment]
Here's a sample MODS identifier:

`<mods:identifier type="type">001122334455</mods:identifier>`

They didn't specifically request the type attribute, but it's safe to assume it should be supported with another column ("Identifier Type").

**Comment by elizoller** [comment]
is this new identifier different or the same from the field in the spreadsheet labeled archives identifier ? (which currently does not map to anything...)

**Comment by sarahjeansweeney** [comment]
It would be a new identifier. "Archives Identifier" is too specific and we want groups other than Archives to be able to create spreadsheets.

**Comment by elizoller** [comment]
Ok, thanks

**Comment by elizoller** [comment]
Changes to spreadsheet:
field "What is the identifier for this object?" changed to "What is the original identifier?" (maps to related item identifier)
field "Identifier X" added (maps to identifier_generic)
field "Identifier Type X " added (maps to identifier_generic.type)
<img width="513" alt="screen shot 2016-11-29 at 9 45 35 am" src="https://cloud.githubusercontent.com/assets/5439169/20714032/ab16d282-b618-11e6-8df0-8c8ac0b2d868.png">
(note in screenshot that identifier 2 will not persist because only the type value is supplied not the identifier itself)
