### ISSUE TITLE
"Add to a Set." modal styling

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#1070]
I noticed today that the "Add to a Set." modal styling is a little different for files than it is for searches and collections:

The file modal (blue "Create New Set" button, rest are green or red):
![file](https://cloud.githubusercontent.com/assets/4663073/21265608/5430a00a-c370-11e6-8fa3-b8f6eb6eb4bd.png)

The search modal (blue "Create New Set" button, rest are blue or red):
![search](https://cloud.githubusercontent.com/assets/4663073/21265625/614d5f12-c370-11e6-830f-08726e8e1d1b.png)

The collection modal (blue "Create New Set" button, rest are blue or red):
![collection](https://cloud.githubusercontent.com/assets/4663073/21265630/6580d65e-c370-11e6-9073-4bf80744c3f5.png)

I think these should be consistent, and the search and collection modals should match the file modal styling.

**Comment by elizoller** [comment]
I'll take a look at it

**Comment by elizoller** [comment]
I think this is working as designed.
On the search results since you are adding more than one file so it would have to check to see if each file was in the set (or in a collection within the set) and then it could display green if all of the files were not in the set or red if all of the files were in the set but then there would be confusion on if some but not all are in the set so it would require a third color like yellow to indicate that some of the items already exist in the set. Also potential significant processing time to loop through each file and check if its the set since search results could be a lot of files. 
I don't see anything specific about this decision in the original ticket (https://github.com/NEU-Libraries/cerberus/issues/730).

**Comment by dgcliff** [comment]
I think we may have decided it after the fact.

**Comment by sarahjeansweeney** [comment]
So the blue is an indication that a check hasn't been made to see if the file(s) already exist in the set?

**Comment by elizoller** [comment]
Yeah, once you click the set it goes through and adds things to the set if it is not there (it won't add dups)

**Comment by dgcliff** [comment]
In v2 I think we'll have a different dynamic (if there even is a modal) - so keep in the back of the mind the quirks/inconsistencies/UX for that

**Comment by sarahjeansweeney** [comment]
👍
