### ISSUE TITLE
Facet line wrapping

### ISSUE THREAD

**Issue by dgcliff** [NEU-Libraries/cerberus#643]
![screenshot 2015-01-29 15 50 53](https://cloud.githubusercontent.com/assets/459084/5966027/ce213b00-a7ce-11e4-9511-10492abc4750.png)

Is it possible to expand out the submenu if there is screen room available? I think this is a side-effect of the fixes for mobile applied earlier.

**Comment by elizoller** [comment]
I think there are a few different options here.

I can set a larger minimum width on the submenu. This will make the width of the submenus more uniform in size and improve readability on some of the submenus with longer titles. It will also create more white space on submenus with short text (ie. year) and affect how much is outside of the viewport.

I can also set the white-space to nowrap on the facet_value which would mean that it wouldn't wrap ever. This is the same style as before. It causes significant issues with the menu being outside the viewport.

Currently, I'm using table display which automatically creates the width of the column based on the breaks in the words of the content so the widths will vary but depend entirely on the text inside. It also has a min-width, that's what is setting the width of submenus with short text (ie. year).

This relates to the issue that no matter how thin we make the submenu, it hangs outside the viewport causing horizontal scroll on most mobile devices. This is not ideal. We could have the submenu open below instead of to the right on mobile devices. Then we could set the width manually to be something relatively reasonable for a mobile device. This may be the best option. We could also then leave nowrap on for larger screen sizes or just set a larger min-width on those.

Any other ideas?

**Comment by dgcliff** [comment]
I think your last suggestion is probably the best. The site needs to be functional on mobile, but it's never going to be the ideal experience (nor should it be expected to be I don't think). Open below on mobile, and nowrap for larger screen sizes should cover most bases I think.

**Comment by elizoller** [comment]
I can't emulate the touch function as well as I'd like to even though chrome dev tools and browser stack. Would it be ok to test this out live? It could potentially break the facet dropdowns (like they were before).

**Comment by dgcliff** [comment]
Try using Vagrant Share to see it on your phone - http://docs.vagrantup.com/v2/share/
