### ISSUE TITLE
MODS key date

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#731]
If possible, the date used for sorting should be taken from the date in the MODS record identified as the keyDate:
```
<mods:originInfo>
    <mods:dateCreated encoding="w3cdtf" keyDate="yes" point="start" qualifier="approximate">1895</mods:dateCreated>
    <mods:dateCreated encoding="w3cdtf" point="end" qualifier="approximate">1918</mods:dateCreated>
</mods:originInfo>
```

**Comment by elizoller** [comment]
The date sorting options are recently created and recently uploaded. Recently created looks at the system_modified date. Recently uploaded looks at the system_create date. 
Are you talking about using the mods dateCreated value for the Recently created sort?
(Date created is the only place in our code that uses the keyDate as far as I can tell but I suppose that a user could change the keyDate with the XML editor in which case we may need to solr-ize the keyDate separately from the dateCreated?)

**Comment by sarahjeansweeney** [comment]
I assumed Recently created was taking the dateCreated value. So right now two photographs uploaded today, one from 1978 and one from 2015, would both use today's date for Recently created?

**Comment by elizoller** [comment]
Yes, As far as I can tell.
Ie. https://repository.library.northeastern.edu/catalog?utf8=%E2%9C%93&sort=system_modified_dtsi+desc&per_page=10&utf8=%E2%9C%93&id=neu%3Arx913r06d&q=boston 
the url shows the sort as system_modified_dtsi and the results for this example present themselves because the archival items

**Comment by dgcliff** [comment]
the difference in those values is fedora date vs. metadata date, isn't it?

**Comment by elizoller** [comment]
metadata date = MODS = user sets
fedora date = system_modified = system generated (not sure if this is fedora or hydra or rails or what not just know that its there)

**Comment by sarahjeansweeney** [comment]
Created can mean different things, but that's more or less ironed out when describing the item. What's in the the dateCreated field is considered the date the item was created, historically created or made into a digital object. We shouldn't use the Fedora/system date for this because that's just the date it was recognized by our system (it may have been digitized and made into an object years ago), and users will use Recently uploaded for that.

**Comment by dgcliff** [comment]
Ok - so @elizoller I think we just need to put in a mapping in mods_datastream to dateCreated keyDate (probably can use a proxy) and then put that value in it's hijacked to_solr section

**Comment by elizoller** [comment]
Ok will look into that

**Comment by elizoller** [comment]
I am thinking this code might actually be in place already and just sort isn't pointing to it.
https://github.com/NEU-Libraries/cerberus/blob/master/app/models/datastreams/mods_datastream.rb#L227 which I think points to https://github.com/NEU-Libraries/cerberus/blob/master/app/models/datastreams/mods_datastream.rb#L341 which has a hierarchy of dates to check for the right date
The only issue I'm seeing is that the .first at the end of L227 indicates the first number of the date string because it is not an array of dates. So the date_ssi field has been storing mostly 1 or 2 (for the beginning of 2015-... or 19....). I think removing .first and changing the sort value (https://github.com/NEU-Libraries/cerberus/blob/master/app/controllers/catalog_controller.rb#L131) to point to date instead of system_modified will fix this.
Test locally and seems to work. If this makes sense then I'll push it up.

**Comment by elizoller** [comment]
Note that this won't really be working until a reindex of core files which will fix the date_ssi
