### ISSUE TITLE
Strange search behavior

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#778]
I've noticed some strange search behavior. I've searched for a few records using metadata I know exists in the record, but I get no results.

Here's an example: https://repository.library.northeastern.edu/files/neu:344030

Nothing comes up when I search for this record using "Le Balbuzard", "Osprey", or "Martinet":

![2015-07-10_1621](https://cloud.githubusercontent.com/assets/4663073/8628306/cbacd4f8-271f-11e5-8b35-57de38c76f71.png)

The record is retrieved when I search for "Balbuzard"

![2015-07-10_1621-1](https://cloud.githubusercontent.com/assets/4663073/8628309/d050f4bc-271f-11e5-8e8c-9c91a943c5b7.png)

**Comment by dgcliff** [comment]
"Martinet" was because of the first name family name split (related to #779) which is working now, as it seems someone clicked the edit button for this item at some point

"Le Balbuzard" doesn't work, because at request, search is strictly AND. "Le" isn't part of the title, it's in the non-sort field.

"Osprey" is in the translated title.

I'll hopefully be able to improve this, as I work through #779 - but again, it's hard to cover all eventualities of MODS
