### ISSUE TITLE
Add embargo to the upload/edit form

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#783]
Uploaders should be able to add an embargo date when uploading a file and should be able to change it on the edit form. This field could be added below the Mass Permissions section.

**Comment by elizoller** [comment]
Do you have specific text in mind for this section?
<img width="1231" alt="screen shot 2015-09-21 at 11 43 53 am" src="https://cloud.githubusercontent.com/assets/5439169/9999423/58ca6468-6064-11e5-8206-b1da55e50d40.png">

**Comment by sarahjeansweeney** [comment]
I like what you have, just remove "embargo": "If this item is embargoed, please enter the release date."

**Comment by elizoller** [comment]
Embargo release date not working on production. This could be due to the fact that it will only save if year, month, and date are selected.

**Comment by elizoller** [comment]
@sarahjeansweeney Since embargo release date (unlike the date created fields) requires a year, month, and day, would you like the fields to be required on the form if a value is selected (ie. if a year is selected then month and day is required) or would you like the values to auto fill (ie. if a year is selected but not a month or day then it will default to jan. 1 of that year)?
Also looking into to how to remove an embargo date (on date created if you set the fields back to the year/month/day default options then it clears the date created out entirely).

**Comment by sarahjeansweeney** [comment]
I think auto fill is a good idea. Most embargo dates are down to the day, but since we're making this available to users who may not be used to the concept, auto fill will prevent some confusion.

**Comment by elizoller** [comment]
With the auto fill do you want it to visually change? Ie. when a user selects a year and not a month/date, it would automatically change the selected value to january 1 
Or do you want it to change after the user submits the form? Ie. if they just select a year and submit the form, it will set month/day to january 1 for them 
Also what if they select a month and/or day and not a year? Do you want it to set to the current year? and what if that date has passed - Then would it go to the next year?

**Comment by dgcliff** [comment]
My vote's that visual change isn't necessary (and adds complicated js to boot)

On functionality - Month only available if year selected, day only available if month selected.

If date has passed - either don't allow them to submit, or don't put it in the dropdown to begin with.

**Comment by sarahjeansweeney** [comment]
I agree with David's suggestions. 

I don't want to make any assumptions on the part of the user, so the date they give us is the date we should use, unless the date has passed, then David's suggestions are good (preferably don't put a date they can't select in the dropdown, but can't submit works, too).

**Comment by elizoller** [comment]
I deployed JS fixes for this to staging.
They establish the following:
- disabling month and day by default until a year is selected
- when year is selected, it enables month
- for embargo release date when year is selected, it checks to see if you've selected the current year and if so, resets the month list to be the current month or future month. 
- when a month is selected, it enables day
- for embargo release date when a month is selected, it checks to see if you've selected the current month and if so, resets the day list to anything in the future from the current day
- if year is set back to the default no value 'Year' option then it disables month and day and resets them to their default values
- if month is set back to the default no value 'Month' option then it disables day and resets it to its default value
- for embargo release day if year is not selected (and thus no month or day is selected), then it fills a nil value which removes the embargo release day
- for embargo release day if a year is selected and not a month (and therefore not a day), it fills the month and day with Jan. 1
- for embargo release day if a year and month are selected and not a day, it fills the day with 1


Questions:
Let's say the value for embargo release day is set for 2016-07-24 and the user changes the value for year to 2015. That would be in the past.  The options for the select dropdowns for month and day adjust to be more in the future than today but because values had been previously selected, it holds on to that value. What should we do in that case? It is the only way I can seem to get past the JS to set a date in the "past"

**Comment by dgcliff** [comment]
Is it possible to put a form submission check to see if the date selected is in the past (and not nil), and then prevent submission?

**Comment by dgcliff** [comment]
@elizoller raised a good point about the edit form, and it presenting old embargo dates. I think allowing people to put in old dates (which would have zero effect on anything) if they want to, greatly simplifies things.

**Comment by dgcliff** [comment]
@elizoller one remaining thing - with the monkey patch of 064dd5164a129aa84264fde24c191d5ff35d8293 can we make it so if the person unselects all values for embargo, it sets the value to nil?

**Comment by elizoller** [comment]
that is in there https://github.com/NEU-Libraries/cerberus/commit/ccd3658811a2a052ede8682a87967e29d2f1177f#diff-e054feda70a4ab67de0b6f2eaec9d994R266
