### ISSUE TITLE
Changes Multiple Accounts

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#843]
A few additions to the YAML changes:

In the login_alert message, "Accounts" in "Please visit your Accounts" should be hyperlinked (http://cerberus.library.northeastern.edu/select_account).

I left the end of the switched_user message empty so the email address could be added to the end.

Can the accounts list be formatted as table with the affiliation, email, and status?:

Affiliation | Email | Status
-------------|---------|---------
Staff | sj.sweeney@neu.edu | Preferred
Student | sweeney.sj@neu.edu | (Set as Preferred button?)

I'd also like to add more text below the list of accounts:

"You can temporarily switch between these accounts at any time by clicking the email address associated with the desired account."

The account icon should be http://fortawesome.github.io/Font-Awesome/icon/paw/

Also, once it's been selected the preferred account should have a visual clue indicating that it is set as the preferred account. I'll leave this up to you guys, though a simple icon works (http://fortawesome.github.io/Font-Awesome/icon/check-circle/)

**Comment by dgcliff** [comment]
Sounds good, thanks

**Comment by sarahjeansweeney** [comment]
Forgot one: when the user sets a primary account or temporarily switches between accounts they should stay on the select_account page rather than being taken to the homepage.

**Comment by elizoller** [comment]
@sarahjeansweeney do you want all references to "preferred" to be changed to "primary"?

**Comment by sarahjeansweeney** [comment]
No, I should have used "preferred" consistently. I'll update the YAML.

**Comment by elizoller** [comment]
Ok thanks

**Comment by elizoller** [comment]
<img width="1220" alt="screen shot 2015-11-25 at 10 13 04 am" src="https://cloud.githubusercontent.com/assets/5439169/11400798/4d64194e-935d-11e5-8056-d217e389b885.png">

**Comment by sarahjeansweeney** [comment]
Looks good!

**Comment by elizoller** [comment]
Fixed with 1726a9a4ccb5b878b9630dd1ebbd4043bba66dc9 701562f97c5f0eb135213f05102c4792772ab74a 
Will deploy to staging later so you can look at it

**Comment by elizoller** [comment]
@sarahjeansweeney this is deployed to staging

**Comment by elizoller** [comment]
what about something like this?
<img width="1244" alt="screen shot 2015-12-01 at 11 57 39 am" src="https://cloud.githubusercontent.com/assets/5439169/11507620/df8f9d88-9822-11e5-8f10-20389adad360.png">

**Comment by dgcliff** [comment]
Looks great. On a purely cosmetic front, I'd put that left column on the far right under a title like..."Action" maybe?

**Comment by sarahjeansweeney** [comment]
Are clicking "Switch to this account" and clicking the email address the same action?

**Comment by elizoller** [comment]
<img width="1226" alt="screen shot 2015-12-01 at 12 01 01 pm" src="https://cloud.githubusercontent.com/assets/5439169/11507687/38eff116-9823-11e5-88f6-5bcaac64e69f.png">

**Comment by dgcliff** [comment]
@sarahjeansweeney I think with the addition of the action column, we could just not make the emails linkable (removing the duplicity)

**Comment by sarahjeansweeney** [comment]
I think the Action and Status column headings should be changed ("Save as preferred" isn't a "Status" compared to "You are currently...."). Status should be changed to Preferred Account and Action should be changed to Status.

Also, the column order should be Status ("You are currently..."), Affiliation, Email, Preferred Account ("Save as preferred..")

**Comment by elizoller** [comment]
<img width="1181" alt="screen shot 2015-12-01 at 12 14 56 pm" src="https://cloud.githubusercontent.com/assets/5439169/11508137/2b17f186-9825-11e5-9b99-c139f49bd638.png">

**Comment by sarahjeansweeney** [comment]
Much better. 
Why is the Status column so wide?
Using the "Switch to this account" is just for the session, correct?

**Comment by elizoller** [comment]
I fixed column width. 
Yes, switching accounts is just for a session. (sessions are fairly long lived - they are reset by a user logging out, clearing cookies, or when we deploy)

As far as the affiliation column goes-  I am concerned about what we could put in that column and how it would look to have nothing or partial data in that column. As of right now, we don't store the affiliation from shib. It's fairly simple to start storing it but it won't be stored until a user logs in with each of their accounts again. That means if they log in for the first time after we deploy the changes and go to manage accounts the account that they just logged in as will have an affiliation value (if there is one in shib) but the other account(s) will not have a value until they log in with those account(s). We could attempt to guess affiliation (by email or whether or not they have an employee object) but since we do not know what we are actually going to get from the affiliation value in shib (since we have never stored it), we could be guessing wrong values. So I'm wondering if would be better to remove the affiliation column.

**Comment by sarahjeansweeney** [comment]
In that case, the "Switch to this account" label should be changed to "Temporarily switch to this account".

If we can't get reliable affiliation data for each account, then I agree the column should be removed.

**Comment by elizoller** [comment]
Ok
