### ISSUE TITLE
System error trying to delete a Set

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#892]
I encountered a system error when I clicked "Request" in the confirmation modal to delete "Eli's Awesome Set".
To replicate,
Go to my shared Set: http://cerberus.library.northeastern.edu/sets/neu:cz30pv23j
Click "Manage Set"
Click "Request" from the "Delete" tab
Error

**Comment by elizoller** [comment]
I'm pretty sure this is a staging variable not set.

**Comment by dgcliff** [comment]
Hm, ok - will look into it. Need to fix the large file upload while I'm at it anyway

**Comment by elizoller** [comment]
Fixed with 79330c8b8d2c97ec2f534565ba65a1c788b03b0b
After submitting, user receives flash saying their request has been submitted.
<img width="1229" alt="screen shot 2016-01-20 at 7 33 07 am" src="https://cloud.githubusercontent.com/assets/5439169/12449016/34abe6e0-bf48-11e5-8c3c-3b0ce0d686fc.png">
For staging, I had it go to me but it is set to go to @sarahjeansweeney on production
<img width="417" alt="screen shot 2016-01-20 at 7 52 39 am" src="https://cloud.githubusercontent.com/assets/5439169/12449377/d76fd736-bf4a-11e5-9d81-2220e1c9903e.png">

**Comment by dgcliff** [comment]
:+1:
