### ISSUE TITLE
"Confirm Navigation" modal for abandoning an upload

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#909]
The modal that appears when a user chooses to navigate away from the metadata page after uploading a file should be updated to match the styling for other modals in the system. 
<img width="844" alt="2016-02-08_1534" src="https://cloud.githubusercontent.com/assets/4663073/12898350/431ac37c-ce7a-11e5-8018-8a21ac46b419.png">

Text should also be updated to:

Your file has been uploaded, but the metadata has not been saved. If you abandon the process now your file will be deleted from the system.
Are you sure you want to leave this page?
Buttons: Delete File\Complete Metadata

**Comment by elizoller** [comment]
Changing the "Your metadata has not been saved..." sentence to "Your file has been uploaded, but..." sentence is no problem but as far as I can tell this particular modal, since it is part of the "onbeforeunload" function can not be modified in appearance or in the button language. 
http://stackoverflow.com/questions/6063522/dialog-box-runs-for-1-sec-and-disappears/6065085#6065085

**Comment by dgcliff** [comment]
Yeah, that's a Javascript restriction, I believe.

**Comment by sarahjeansweeney** [comment]
Booo. Oh well. Just the text change is fine, then.
