### ISSUE TITLE
Consolidate core file tabs

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#911]
We have six possible tabs for each core file (metadata, associated files, edit, move, delete, and XML). Can the edit, move, delete, and XML tabs be consolidated into one Manage File tab, just like the "Manage Collection" tabs?
<img width="795" alt="2016-02-08_1603" src="https://cloud.githubusercontent.com/assets/4663073/12899082/c3e2df00-ce7d-11e5-9369-92cdcd2139f9.png">

The page title for the consolidated tabs should be "Manage [title]".

**Comment by elizoller** [comment]
By "Manage [title]" do you want the title of the core file to be in the tab name?

**Comment by elizoller** [comment]
Do you want the page title to be "Edit [title]" instead of "Edit Metadata" now?
<img width="1217" alt="screen shot 2016-02-09 at 10 58 32 am" src="https://cloud.githubusercontent.com/assets/5439169/12923628/729786a8-cf24-11e5-8263-dcbd8533cf01.png">




![screen shot 2016-02-09 at 11 59 58 am](https://cloud.githubusercontent.com/assets/5439169/12923692/a45b6376-cf24-11e5-9ecf-f4d4c6748f90.png)
![screen shot 2016-02-09 at 12 00 04 pm](https://cloud.githubusercontent.com/assets/5439169/12923691/a4400a68-cf24-11e5-9fa2-abb59d2d883e.png)

![screen shot 2016-02-09 at 12 00 08 pm](https://cloud.githubusercontent.com/assets/5439169/12923689/a42ee8dc-cf24-11e5-88f6-45b49d0134f8.png)

**Comment by sarahjeansweeney** [comment]
I'd like it to be "Manage [core file title]" instead - thanks.

**Comment by elizoller** [comment]
Ok, Just verifying because titles can be long. Do you want the title in italics?

**Comment by sarahjeansweeney** [comment]
Yes, italics would be great.

**Comment by elizoller** [comment]
<img width="1262" alt="screen shot 2016-02-09 at 12 16 54 pm" src="https://cloud.githubusercontent.com/assets/5439169/12924213/fb2026ae-cf26-11e5-9f39-b95e045c9f30.png">

**Comment by dgcliff** [comment]
I'm a little worried too - when we do #883 there are lots of titles that'll overflow the tab area.

Could we do Manage Item instead?

**Comment by sarahjeansweeney** [comment]
I'm sorry, @elizoller, I misunderstood your original question about the tab name. I don't think the tab title needs the full core file title (you're right, those can get long). Just "Manage File" should be fine for the tab title. The full edit move, etc page can have the core file title.

**Comment by elizoller** [comment]
Gotcha.

**Comment by elizoller** [comment]
@sarahjeansweeney I deployed to staging with this fix. Do you want to check it out and make sure it's what you're looking for?

**Comment by sarahjeansweeney** [comment]
Sure! Mostly looks good. I just noticed two things:

- Can the edit page title be "Manage [core file title]"?:
![2016-02-09_1335](https://cloud.githubusercontent.com/assets/4663073/12926559/0a1d581a-cf32-11e5-9ca3-6e9a6642ffbf.png)

- I can switch easily from the edit tab to the other tabs, but clicking on the edit tab again does nothing, it just adds ```#edit``` to the end of the url (http://cerberus.library.northeastern.edu/files/neu:cz30pv759/edit#edit).
