### ISSUE TITLE
MODS Spreadsheet loader removed handle

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#971]
I used the MODS spreadsheet loader to test a single upload this morning, which worked well for the most part: https://repository.library.northeastern.edu/files/neu:rx914f73k

The load report included a message about the Handle ("Modified - Handle does not match") and the handle was removed from the MODS record.

As far as I can tell, the Handles do in fact match:
From spreadsheet: http://hdl.handle.net/2047/D20129023
From original MODS: http://hdl.handle.net/2047/D20129023

Even if they didn't match, the original handle should not have been removed from the record.

**Comment by elizoller** [comment]
I think this record failed because it could not get the previous handle.
Looking at this record in MODS revision history, the file as of 6/15 has the handle stored like `<mods:identifier type="uri">http://hdl.handle.net/2047/D20129023</mods:identifier>`
When I manually edited a record locally to have this as the handle (and disabled the validation check for the proper handle formatting), and then ran the loader, it wasn't able to retrieve the identifier from the original record, which is where it assigns it from. 
Looking into a backup check if it can't retrieve the normal way (and fix the attributes in this process.
