### ISSUE TITLE
Spreadsheet loader: clicking files or metadata doesn't reveal upload options

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#999]
I tried to load metadata using the spreadsheet loader this morning. When I click one of the buttons  to select the upload option (new files + metadata or metadata only), the upload options aren't revealed below:

![2016-08-02_1114](https://cloud.githubusercontent.com/assets/4663073/17334020/b348e52c-58a2-11e6-8747-4c595101143a.png)

Here's a screencast of it: http://screencast.com/t/fKR4sN8iul

I tried a hard refresh. In the past I had noticed that I had to click the button twice, but no number of clicking brings up the upload options. 

Although, it may just be taking a while to load. I left the page up while I was writing this ticket, and clicking the buttons again now, the options loaded:

![2016-08-02_1122](https://cloud.githubusercontent.com/assets/4663073/17334237/760d0e94-58a3-11e6-9a5c-adf423365de7.png)

**Comment by elizoller** [comment]
Ok, I'll look into it.

**Comment by elizoller** [comment]
I thought maybe the JS controlling this was inefficient so I reconfigured it to load the forms prior to the page loading instead of reaching out for them via AJAX.
Tested locally with no issues. 
But seeing it on production, it has just deferred the load time from behind the button to the page load itself. This is due to the processing work involved in creating the forms. For the new files form, it has to query for all collections and then filter through the collections to see which ones the user has the ability to upload to.
I'm going to try caching the all collections query response. I think this will help response time.

**Comment by elizoller** [comment]
The solution I've come up with is to cache the collection count and cache the query results of all of the collections (just pid and title, this is an expensive query on prod because of the number of collections). Then each time the page loads, it checks the cached collection count number and gets the count again and compares these two numbers. If they aren't equal, then it forces the all collections query to be run again (ensuring that if there are new collections made, they will show up). Then after the all collections query is either retrieved from cache or run, then it will loop through checking the users permissions. This is all depends on if the time consuming part of the page load is actually doing the query and not the part where it has to loop through for permissions.
Another possible solution (or add on) that could involve the user would be to store the results of the filtered collections as a session variable. But I'm a little concerned about the size of those results and if that much data can/should be stored in a session variable.

**Comment by elizoller** [comment]
Locally the solution with caching the all collections query has taken page load from around 5.7 seconds to 3.5 seconds which feels good to me but I'm not sure what it will be like on prod since the page on prod takes ~1 minute to load right now.
